### ISSUE TITLE
Main and Backup BTC Servers

### ISSUE THREAD

**Issue by ashaw1131** [mining-pool/not-only-mining-pool#2]
Since it is industry standard to have a main node and a backup node, would it be possible to add a second server for this connect to if a main server goes down? For redundancy issues.

**Scenario**
Stratum Server is connected to main btc node, main btc node goes down, stratum server instantly connects to a backup btc node and continues to serve jobs. 

Most Stratum services that I have seen offer this capability so this is just an idea.

**Comment by C0MM4ND** [comment]
This feature has been implemented. Just add more daemon objects in daemons field like this.

```
  "daemons": [
    {
      "host": "127.0.0.1",
      "port": 18332,
      "user": "bitcoinrpc",
      "password": "testnet"
    },
    {
      "host": "127.0.0.1",
      "port": 18334,
      "user": "bitcoinrpc",
      "password": "testnet",
      "tls": {}
    }
  ],
```

- BlockTempleate will be provided by the first available(survival) daemon. 
- Every Block mined by pool will be submitted to every daemon.

**Comment by ashaw1131** [comment]
With two nodes running, one is bicoind, the other is BTC
Config as per above

```
go run main.go
{"id":1638792583640525514,"method":"getpeerinfo","params":[]}
2020-10-18T14:17:27.303-0500	PANIC	daemonMgr	failed to unmarshal response body: 
panic: failed to unmarshal response body: 

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001120b0, 0x0, 0x0, 0x0)
	/home/$user/go/pkg/mod/go.uber.org/zap@v1.14.1/zapcore/entry.go:230 +0x55f
go.uber.org/zap.(*SugaredLogger).log(0xc0000a85e0, 0x4, 0x8dedb6, 0x25, 0xc000191bd0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/$user/go/pkg/mod/go.uber.org/zap@v1.14.1/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/home/$user/go/pkg/mod/go.uber.org/zap@v1.14.1/sugar.go:159
github.com/mining-pool/not-only-mining-pool/daemonManager.(*DaemonManager).CmdAll(0xc00009bc20, 0x8d3c29, 0xb, 0xbf5210, 0x0, 0x0, 0xc000191d68, 0x7c8e8c, 0x87f7a0, 0xc00009bc20, ...)
	/home/$user/go/src/github.com/not-only-mining-pool/daemonManager/daemonManager.go:153 +0x89a
github.com/mining-pool/not-only-mining-pool/daemonManager.(*DaemonManager).IsAllOnline(0xc00009bc20, 0x5)
	/home/$user/go/src/github.com/not-only-mining-pool/daemonManager/daemonManager.go:55 +0x69
github.com/mining-pool/not-only-mining-pool/daemonManager.(*DaemonManager).Check(0xc00009bc20)
	/home/$user/go/src/github.com/not-only-mining-pool/daemonManager/daemonManager.go:49 +0x2f
github.com/mining-pool/not-only-mining-pool/poolManager.NewPool(0xc0000babe0, 0x84c3e0)
	/home/$user/go/src/github.com/not-only-mining-pool/poolManager/pool.go:47 +0x7b
main.main()
	/home/$user/go/src/github.com/not-only-mining-pool/main.go:47 +0x399
exit status 2

```

**Comment by ashaw1131** [comment]
Disregard, I will re open if it pops any more errors

**Comment by ashaw1131** [comment]
Missed the point of this I guess, when one goes down, the pool halts, it should switch to the next server

**Comment by C0MM4ND** [comment]
This is a standalone server not a portal nor web engine, so it doesn't sense any other pool and cannot do stream forwarding when it panic. 

It would be better to get load balance/DDoS protection services from cloud computing service/other professional firmware, which will be more stable than running a software.

So currently this feature won't be implemented.
