### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by swanseahost** [mining-pool/not-only-mining-pool#6]
When running go build .

main.go:4:2: cannot find package "encoding/json" in any of:
        /root/go/src/encoding/json (from $GOROOT)
        /root/work/src/encoding/json (from $GOPATH)
main.go:5:2: cannot find package "flag" in any of:
        /root/go/src/flag (from $GOROOT)
        /root/work/src/flag (from $GOPATH)
main.go:8:2: cannot find package "github.com/ipfs/go-log/v2" in any of:
        /root/go/src/github.com/ipfs/go-log/v2 (from $GOROOT)
        /root/work/src/github.com/ipfs/go-log/v2 (from $GOPATH)
main.go:9:2: cannot find package "github.com/mining-pool/not-only-mining-pool/config" in any of:
        /root/go/src/github.com/mining-pool/not-only-mining-pool/config (from $GOROOT)
        /root/work/src/github.com/mining-pool/not-only-mining-pool/config (from $GOPATH)
main.go:10:2: cannot find package "github.com/mining-pool/not-only-mining-pool/pool" in any of:
        /root/go/src/github.com/mining-pool/not-only-mining-pool/pool (from $GOROOT)
        /root/work/src/github.com/mining-pool/not-only-mining-pool/pool (from $GOPATH)
main.go:11:2: cannot find package "github.com/mining-pool/not-only-mining-pool/utils" in any of:
        /root/go/src/github.com/mining-pool/not-only-mining-pool/utils (from $GOROOT)
        /root/work/src/github.com/mining-pool/not-only-mining-pool/utils (from $GOPATH)
main.go:6:2: cannot find package "os" in any of:
        /root/go/src/os (from $GOROOT)
        /root/work/src/os (from $GOPATH)
package .
        imports runtime: cannot find package "runtime" in any of:
        /root/go/src/runtime (from $GOROOT)
        /root/work/src/runtime (from $GOPATH)

**Comment by c0mm4nd** [comment]
please reinstall your golang and build pool with a **clean** golang >= 1.14
